HTML=r'''<!doctype html><html lang="bg"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Sofia Digital Archive</title>
<style>:root{--ink:#211d19;--paper:#f4efe4;--red:#8b1e1e;--muted:#746b62;--line:#d8cfc2;--ok:#246b45;--warn:#a56612}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px system-ui,sans-serif}header{background:#211d19;color:white;padding:20px max(24px,calc((100% - 1250px)/2));display:flex;justify-content:space-between;align-items:center}header h1{margin:0;font-family:Georgia,serif}.shell{max-width:1250px;margin:auto;padding:24px}.tabs{display:flex;gap:8px;border-bottom:1px solid var(--line);margin-bottom:22px}.tabs button{border:0;background:transparent;padding:13px 18px;font-weight:700;font-size:16px}.tabs button.active{color:var(--red);border-bottom:3px solid var(--red)}button,.button,input,textarea,select{font:inherit;padding:10px 12px}button,.button{cursor:pointer;border:1px solid #9d9285;background:white;border-radius:4px}button.primary{background:var(--red);color:white;border-color:var(--red)}button:disabled{opacity:.5;cursor:not-allowed}.workspace{display:none}.workspace.active{display:block}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}.stat,.card,.panel{background:white;border:1px solid var(--line);border-radius:6px;padding:18px}.stat strong{display:block;font-size:28px}.muted{color:var(--muted)}.status{display:inline-block;padding:3px 8px;border-radius:20px;background:#eee}.status.complete,.status.approved,.status.pass{background:#dcefe4;color:var(--ok)}.status.failed,.status.needs_work{background:#f7dddd;color:#8b1e1e}.status.pending,.status.running,.status.review{background:#fff0ce;color:var(--warn)}table{width:100%;border-collapse:collapse;background:white}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--line);vertical-align:top}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:14px 0}.split{display:grid;grid-template-columns:minmax(340px,1fr) minmax(340px,1fr);gap:18px}.scan{width:100%;max-height:650px;object-fit:contain;background:#ddd}.crop{width:100%;max-height:650px;object-fit:contain;background:#eee}.review-card{margin-bottom:18px}.review-controls textarea{width:100%;height:220px}.searchbox{width:min(700px,75%)}article.result{background:white;margin:12px 0;padding:18px;border-left:4px solid var(--red)}.error{color:#a00}.success{color:var(--ok)}dialog{width:min(1100px,95vw);border:0;border-radius:8px;padding:22px}dialog::backdrop{background:#0008}@media(max-width:760px){.split{grid-template-columns:1fr}header{display:block}.tabs{overflow:auto}}</style>
<header><div><h1>Sofia Digital Archive</h1><div>Digitisation, review, and research</div></div><div id=connection>Connecting…</div></header><div class=shell>
<nav class=tabs><button data-testid=operations-tab class=active onclick="openWorkspace('operations')">Operations</button><button data-testid=review-tab onclick="openWorkspace('review')">Review</button><button data-testid=research-tab onclick="openWorkspace('research')">Research</button></nav>
<section id=operations class="workspace active"><h2>Operations</h2><p class=muted>Upload scans into a batch, select exactly what to run, then process it.</p><div id=opstats class=grid></div><div class="card"><h3>1. New batch</h3><div class=toolbar><input id=batchname aria-label="Batch name" placeholder="Batch name"><button data-testid=create-batch onclick=createBatch()>Create batch</button><label class=button>Upload one or more scans<input id=upload type=file accept="image/png,image/jpeg,image/tiff" multiple hidden onchange=uploadFiles(this.files)></label></div><p id=activebatch class=muted>No active batch.</p><div id=batchscans></div><h3>2. Process</h3><div class=toolbar><label><input type=radio name=mode value=qc checked> QC only</label><label><input type=radio name=mode value=full> Full digitisation</label><button data-testid=process-selected class=primary onclick=processSelected()>Process selected scans</button></div><p id=opmsg></p></div><h3>Stage progress</h3><div id=timeline></div><h3>Recent batches</h3><div id=batches></div><h3>Processing jobs</h3><div id=jobs></div></section>
<section id=review class=workspace><h2>Review</h2><p class=muted>Approve pages and correct disputed or incomplete regions.</p><div class=toolbar><button onclick=loadReviewPages()>Pages & QC</button><button onclick=loadRegionReviews()>OCR queue</button></div><div id=reviewcontent></div></section>
<section id=research class=workspace><h2>Research</h2><p>Search reconstructed archival text and inspect its exact scan evidence.</p><div class=toolbar><input class=searchbox id=q aria-label="Search query" placeholder="Търсене…"><button data-testid=search-button class=primary onclick=searchArchive()>Search</button></div><div id=results></div><div id=evidence></div></section></div>
<dialog id=reviewdialog><button style="float:right" onclick=reviewdialog.close()>Close</button><div id=dialogcontent></div></dialog>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async(url,opts={})=>{let r=await fetch(url,opts);if(!r.ok)throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail||r.statusText);return r.json()};
function openWorkspace(id){document.querySelectorAll('.workspace').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.testid===id+'-tab'));if(id==='operations')loadOperations();if(id==='review')loadReviewPages()}
const badge=s=>`<span class="status ${esc(s)}">${esc(s)}</span>`;
let currentBatch=null,apiReady=false;
async function loadOperations(){try{let d=await api('/api/operations/summary');apiReady=d.api_key_configured;connection.textContent='Backend connected';opstats.innerHTML=`<div class=stat><span>Digitized pages</span><strong>${d.database.pages}</strong></div><div class=stat><span>Articles</span><strong>${d.database.articles}</strong></div><div class=stat><span>Open reviews</span><strong>${d.open_reviews}</strong></div><div class=stat><span>Failed jobs</span><strong>${d.failed_jobs}</strong></div><div class=stat><span>OpenAI API</span><strong>${apiReady?'Ready':'Not set'}</strong></div>`;jobs.innerHTML=d.jobs.length?`<table><tr><th>ID</th><th>Stage</th><th>Status</th><th>Attempts</th><th>Error</th></tr>${d.jobs.map(j=>`<tr><td>${j.job_id}</td><td>${esc(j.stage)}</td><td>${badge(j.status)}</td><td>${j.attempts}</td><td>${esc(j.error||'')}</td></tr>`).join('')}</table>`:'<p>No jobs yet.</p>';let bs=await api('/api/operations/batches');batches.innerHTML=bs.length?`<table><tr><th>Batch</th><th>Scans</th><th>Mode</th><th>Status</th></tr>${bs.map(b=>`<tr onclick="openBatch('${b.batch_id}')"><td><button>${esc(b.name)}</button></td><td>${b.scan_count}</td><td>${esc(b.mode||'—')}</td><td>${badge(b.status)}</td></tr>`).join('')}</table>`:'<p>No batches yet.</p>';if(currentBatch)await openBatch(currentBatch)}catch(e){connection.textContent='Backend unavailable';opmsg.className='error';opmsg.textContent=e.message}}
async function startRun(mode){opmsg.className='';opmsg.textContent='Starting…';try{let d=await api('/api/operations/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});opmsg.className='success';opmsg.textContent=`Job #${d.job_id} started.`;loadOperations()}catch(e){opmsg.className='error';opmsg.textContent=e.message}}
async function retryJob(id){await api(`/api/operations/jobs/${id}/retry`,{method:'POST'});loadOperations()}
async function createBatch(){let name=batchname.value.trim()||`Batch ${new Date().toLocaleString()}`;let d=await api('/api/operations/batches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});currentBatch=d.batch_id;batchname.value='';await openBatch(currentBatch);loadOperations()}
async function uploadFiles(files){if(!currentBatch)await createBatch();for(let file of files){let form=new FormData();form.append('file',file);try{await api(`/api/operations/batches/${currentBatch}/upload`,{method:'POST',body:form});opmsg.className='success';opmsg.textContent=`Uploaded ${file.name}` }catch(e){opmsg.className='error';opmsg.textContent=`${file.name}: ${e.message}`}}await openBatch(currentBatch);loadOperations()}
async function openBatch(id){currentBatch=id;let d=await api('/api/operations/batches/'+id);activebatch.innerHTML=`Active batch: <strong>${esc(d.batch.name)}</strong> · ${badge(d.batch.status)}`;batchscans.innerHTML=d.scans.length?`<table><tr><th>Select</th><th>Scan</th><th>Current stage</th></tr>${d.scans.map(s=>`<tr><td><input aria-label="Select ${esc(s.filename)}" type=checkbox ${s.selected?'checked':''} onchange="toggleScan('${s.scan_id}',this.checked)"></td><td>${esc(s.filename)}</td><td>${badge(s.status)}</td></tr>`).join('')}</table>`:'<p>Upload scans to this batch.</p>';timeline.innerHTML=d.scans.map(s=>`<div class=card><strong>${esc(s.filename)}</strong><p>${s.events.map(e=>badge(e.stage)).join(' → ')||'Uploaded'}</p></div>`).join('')||'<p>No stage events yet.</p>'}
async function toggleScan(id,selected){await api(`/api/operations/batches/${currentBatch}/scans/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({selected})})}
async function processSelected(){if(!currentBatch){opmsg.className='error';opmsg.textContent='Create a batch and upload scans first.';return}let mode=document.querySelector('input[name=mode]:checked').value;if(mode==='full'&&!apiReady){opmsg.className='error';opmsg.textContent='Add OPENAI_API_KEY before full digitisation. QC only works now.';return}try{let d=await api(`/api/operations/batches/${currentBatch}/process`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,scan_ids:[]})});opmsg.className='success';opmsg.textContent=`Processing ${d.selected_count} selected scan(s) in job #${d.job_id}.`;await loadOperations()}catch(e){opmsg.className='error';opmsg.textContent=e.message}}
async function loadReviewPages(){let d=await api('/api/review/pages');reviewcontent.innerHTML=d.length?`<table><tr><th>Page</th><th>QC</th><th>Open OCR</th><th>Approval</th><th></th></tr>${d.map(p=>{let name=p.source_path.split(/[\\/]/).pop().replace(/\.[^.]+$/,'');return `<tr><td>${esc(name)}</td><td>${badge(p.qc_status||'unknown')}</td><td>${p.open_reviews}</td><td>${badge(p.approval_status)}</td><td><button onclick="inspectPage('${esc(p.page_id)}')">Inspect</button></td></tr>`}).join('')}</table>`:'<p>No digitized pages.</p>'}
async function inspectPage(id){let d=await api('/api/pages/'+encodeURIComponent(id)),qc=JSON.parse(d.page.qc_json);dialogcontent.innerHTML=`<h2>${esc(id.split(':').pop())}</h2><div class=split><div><img class=scan alt="Page scan" src="/api/page-images/${encodeURIComponent(id)}"></div><div><h3>Quality control</h3><p>${(qc.flags||[]).map(badge).join(' ')||badge('pass')}</p><pre>${esc(JSON.stringify(qc.scores||{},null,2))}</pre><h3>Layout</h3><p>${d.regions.length} regions in reading order.</p><div class=toolbar><button class=primary onclick="approvePage('${esc(id)}','approved')">Approve page</button><button onclick="approvePage('${esc(id)}','needs_work')">Needs work</button></div><p id=approvalmsg></p></div></div>`;reviewdialog.showModal()}
async function approvePage(id,status){await api('/api/review/pages/'+encodeURIComponent(id)+'/approval',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,reviewer:'local-reviewer',note:''})});approvalmsg.textContent='Saved: '+status;loadReviewPages()}
async function loadRegionReviews(){let d=await api('/api/reviews');reviewcontent.innerHTML=d.map(x=>`<article class="card review-card"><div class=split><img class=crop alt="Region crop" src="/api/regions/${encodeURIComponent(x.region_id)}/image?variant=1"><div class=review-controls><h3>OCR review #${x.review_id}</h3><p>${esc(JSON.parse(x.reasons_json).join(', ').replaceAll('_',' '))}</p><textarea aria-label="Correction ${x.review_id}" id="c${x.review_id}" placeholder="Complete diplomatic transcription"></textarea><button class=primary onclick="resolveReview(${x.review_id})">Save correction</button><p class=error id="e${x.review_id}"></p></div></div></article>`).join('')||'<p>No open OCR reviews.</p>'}
async function resolveReview(id){let value=document.getElementById('c'+id).value.trim();if(!value){document.getElementById('e'+id).textContent='Correction cannot be empty.';return}await api('/api/reviews/'+id+'/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({correction:value,reviewer:'local-reviewer'})});loadRegionReviews()}
async function searchArchive(){let d=await api('/api/search?q='+encodeURIComponent(q.value));results.innerHTML=d.results.map(x=>`<article class=result><h3>${esc(x.title||'Untitled')}</h3><p>${esc(x.normalized_text)}</p><small>${esc(x.page_id)} · confidence ${x.confidence??'unreviewed'}</small><p><button onclick="showEvidence('${esc(x.page_id)}')">View evidence</button></p></article>`).join('')||'<p>No results.</p>'}
async function showEvidence(id){let d=await api('/api/pages/'+encodeURIComponent(id));evidence.innerHTML=`<div class=panel><h2>Evidence</h2><div class=split><img class=scan alt="Original scan" src="/api/page-images/${encodeURIComponent(id)}"><div><h3>${esc(id.split(':').pop())}</h3><p>${d.regions.length} linked regions</p><ol>${d.regions.map(r=>`<li>${esc(r.type)} — ${esc(r.verbatim_text||'[pending transcription]')}</li>`).join('')}</ol></div></div></div>`;evidence.scrollIntoView()}
loadOperations();
</script></html>'''
